version: "3.5"

services:
  kurento-examples:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kurento-example
    depends_on:
      - kurento
    ports:
      - 8443:8443
    networks:
      - default
    environment:
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
      - "APP_SERVER_HOST=kurento-examples"
      - "APP_SERVER_PORT=8443"
      - "TUTORIAL_NAME=hello-world"

  kurento:
    image: kurento/kurento-media-server
    hostname: kurento
    container_name: kurento-kms
    expose:
      - "8888"
    ports:
      - 8888:8888
    networks:
      - default

# networks:
#   default:
    # ipam:
    #   config:
    #     - subnet: 172.18.1.0/24